# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20161013_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, help_text='Maximum file size allowed is 5Mb', null=True, upload_to='questionAudio', validators=[qa.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 2Mb', null=True, upload_to='questionImages', validators=[qa.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, help_text='Maximum file size allowed is 10Mb', null=True, upload_to='questionVideo', validators=[qa.validators.validate_video]),
        ),
    ]
