# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import qa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20161017_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the grade name', max_length=10, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the level name', max_length=10, verbose_name='name')),
                ('threshold', models.IntegerField(help_text='Enter the threshold in percentage (max 100)', verbose_name='threshold')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='qa.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttemptPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(blank=True, null=True)),
                ('second', models.IntegerField(blank=True, null=True)),
                ('third', models.IntegerField(blank=True, null=True)),
                ('fourth', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 2Mb', null=True, upload_to='article', validators=[qa.validators.validate_image]),
        ),
        migrations.AddField(
            model_name='article',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='qa.Level'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='grade',
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title', 'level', 'category')]),
        ),
    ]
