# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_article_content_formatted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
