# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_remove_article_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set([('name', 'grade')]),
        ),
    ]
